# Generated by Django 5.2.7 on 2025-10-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('number_affected', models.IntegerField()),
                ('narcan_doses_administered', models.IntegerField(blank=True, null=True)),
                ('report_text', models.TextField(max_length=300)),
                ('fatal_incident', models.BooleanField()),
            ],
        ),
    ]
