# Generated by Django 5.2.7 on 2025-10-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='datetime',
            field=models.DateTimeField(unique=True),
        ),
    ]
