# Generated by Django 5.2.7 on 2025-10-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_incident_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='report_text',
            field=models.TextField(max_length=500),
        ),
    ]
