# Generated by Django 5.2.7 on 2025-10-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_incident_latitude_incident_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.AddField(
            model_name='incident',
            name='coordinates',
            field=models.CharField(blank=True, help_text='Latitude, Longitude (e.g. "47.6567, -117.4234")', max_length=50, null=True),
        ),
    ]
