# Generated by Django 5.2.7 on 2025-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_incident_latitude_remove_incident_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
